### PR TITLE
359 Django Breaking Code Updates

### PR DESCRIPTION
**Pull request by Xunrise**
Fixes the mentioned issue by updating imports. 
Might want to move the static import from the templates into a base template.

### CODE REVIEW

**Comment by merforga** [comment]
=o i didnt realise people were still working on this ^^

**Comment by Xunrise** [comment]
Trying to revive as we talked about in the discord :> Can also close #359

**Comment by gw2princeps** [comment]
Where do you coordinate @MartinGalu ? Discord? I'd be interested in following along maybe :)

**Comment by Xunrise** [comment]
@gw2princeps doing it mostly alone rn until its at a maintainable point

**Pull request merged**
